update

diff --git a/tester/Makefile b/tester/Makefile
--- a/tester/Makefile
+++ b/tester/Makefile
@@ -6,7 +6,7 @@
 #    By: uakizuki <uakizuki@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2025/07/17 05:54:22 by uakizuki          #+#    #+#              #
-#    Updated: 2025/07/20 09:19:27 by uakizuki         ###   ########.fr        #
+#    Updated: 2025/07/20 09:49:22 by uakizuki         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -28,18 +28,18 @@ endif
 
 test: $(WEBSERV) $(CONFIGURE_JSON) tester cgi_tester
 	@{ \
+	  STATUS=1 ; \
 	  $(WEBSERV) $(CONFIGURE_JSON) & \
-	  PID=$$!; \
-	  sleep 1; \
-	  kill -0 $$PID \
-	  ./tester http://localhost:4242 </dev/null | grep '^Test'; \
-	  STATUS="$${PIPESTATUS[0]}"; \
-	  read -p "Press Enter to continue..." -r; \
-	  kill -INT $$PID; \
-	  wait $$PID; \
-	  if [ $$STATUS -ne 0 ]; then \
-	    echo "Tests failed"; \
-	  fi; \
+	  PID=$$! ; \
+	  sleep 1 ; \
+	  kill -0 $$PID && { \
+	    ./tester http://localhost:4242 </dev/null | grep '^Test' ; \
+	    STATUS="$${PIPESTATUS[0]}" ; \
+	    read -p "Press Enter to continue..." -r ; \
+	    kill -INT $$PID ; \
+	    wait $$PID || true ; \
+	  } ; \
+	  ( exit $$STATUS ) || echo "Tests failed" ; \
 	}
 
 run: $(WEBSERV) $(CONFIGURE_JSON) tester cgi_tester
